### ISSUE TITLE
[Feature Request] Text fade in "Animation"

### ISSUE THREAD

**Issue by dalesnail** [Aiue/AQT#34]
So the idea here would essentially be to have an option to have quest text fade in when expanding a section/header/zone. 

Similar to the way quest text works when you _don't_ have the "Instant quest text" option chosen in interface. Maybe not fully animated in that way, was thinking more of just a 0.75-1 second alpha fade in. 

Also since the sound options already exist, could have that notebook writing sound on expand as well, but I'm %100 sure that would get real old, real quick haha. But maybe some RPers would like it?

Obviously not high prio, but I think this option would make the addon look nicer if it's possible. Smoother transitions with any text or frame, sort of lend themselves to a more "polished" feel in my opinion.

**Comment by Aiue** [comment]
Just did some experimentation for fading. Tried having it possible to have the tracker fade out when the mouse is not over it, but it seems as soon as the mouse moves over something with a mouseclick script on it, it acts as though the mouse leaves the frame. So that will require some further tweaking.

Fading the text in should be a fairly simple task, I just need to plan it properly, since it should definitely be doable without having to create an animationgroup for every single entry.

I'm also thinking I want to have a slight delay in when the animations start for each entry. So that the first line is always the first to fade in, and last to fade out. The second line the second to fade in, second last to fade out, and so on. Shouldn't be too hard to do, once I figure out which specific way of doing it I want to go with.
